const DummyData = [
  {
    id: 1,
    first_name: "Christabel",
    last_name: "Thursby",
    email: "cthursby0@mapy.cz",
    gender: "Genderfluid",
    ip_address: "169.159.231.234",
  },
  {
    id: 2,
    first_name: "Rora",
    last_name: "Skase",
    email: "rskase1@phoca.cz",
    gender: "Female",
    ip_address: "86.205.170.105",
  },
  {
    id: 3,
    first_name: "Baxie",
    last_name: "Downgate",
    email: "bdowngate2@slideshare.net",
    gender: "Male",
    ip_address: "194.14.174.123",
  },
  {
    id: 4,
    first_name: "Mickie",
    last_name: "Clendening",
    email: "mclendening3@jugem.jp",
    gender: "Male",
    ip_address: "252.218.110.187",
  },
  {
    id: 5,
    first_name: "Gisele",
    last_name: "Hanham",
    email: "ghanham4@slideshare.net",
    gender: "Female",
    ip_address: "43.186.99.164",
  },
  {
    id: 6,
    first_name: "Freddie",
    last_name: "Nystrom",
    email: "fnystrom5@virginia.edu",
    gender: "Male",
    ip_address: "180.70.43.70",
  },
  {
    id: 7,
    first_name: "Reagan",
    last_name: "Weafer",
    email: "rweafer6@hostgator.com",
    gender: "Male",
    ip_address: "237.128.236.38",
  },
  {
    id: 8,
    first_name: "Aveline",
    last_name: "Arnaud",
    email: "aarnaud7@cnet.com",
    gender: "Female",
    ip_address: "108.27.186.129",
  },
  {
    id: 9,
    first_name: "Alexi",
    last_name: "Mountlow",
    email: "amountlow8@squarespace.com",
    gender: "Female",
    ip_address: "165.126.155.111",
  },
  {
    id: 10,
    first_name: "Jana",
    last_name: "Wilkin",
    email: "jwilkin9@indiegogo.com",
    gender: "Female",
    ip_address: "136.15.40.251",
  },
];

module.exports = DummyData;
